### ISSUE TITLE
Prepare for Release

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#104]
- [x] Create release tag for latest version 
- [x] Create/Update .env file 
- [x] Finish Deployment doku
- [x] Finish Changelog doku
- [x] Send Meeting agenda to customers
- [x] Finish user stories doku
- [x] add https://github.com/ait-cs-IaaS/Taranis-NG/wiki/New-Ideas-from-Meeting to issue tracker

**Comment by b3n4kh** [comment]
Released with:

```
containers=(ghcr.io/ait-cs-iaas/taranis-ng-collectors ghcr.io/ait-cs-iaas/taranis-ng-core ghcr.io/ait-cs-iaas/taranis-ng-gui ghcr.io/ait-cs-iaas/taranis-ng-presenters ghcr.io/ait-cs-iaas/taranis-ng-publishers)
for c in "${containers[@]}"; do docker tag $c:latest $c:bmi_poc && docker push $c:bmi_poc; done
```
