### ISSUE TITLE
ForeignKey Constraint issues

### ISSUE THREAD

**Issue by b3n4kh** [ait-cs-IaaS/Taranis-NG#117]
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation)

Various Tables do not cleanly cascade on delete:

- [x]  Roles => role_permission
- [x]  OSINTSource => parameter_values
- [x]  Reports => report_item_attribute
- [x] User delete --> when roles are set
* [....] ?

**Comment by b3n4kh** [comment]
Most probably related to: #73

**Comment by ewoiset** [comment]
on user delete  (when roles are set) `ERROR:  update or delete on table "user" violates foreign key constraint "user_role_user_id_fkey" on table "user_role"`

**Comment by ewoiset** [comment]
this  issue mainly handles user foreign key constraints. Follow-up issue: https://github.com/ait-cs-IaaS/Taranis-NG/issues/136
