### ISSUE TITLE
Analyze issues

### ISSUE THREAD

**Issue by b3n4kh** [ait-cs-IaaS/Taranis-NG#120]
- [ ] enable RICH_TEXT & Attribute CVSS display
- [x]  Adapt color scheme from "Side-by-side" and "Completed"

**Comment by ewoiset** [comment]
realted issues: https://github.com/ait-cs-IaaS/Taranis-NG/issues/107 https://github.com/ait-cs-IaaS/Taranis-NG/issues/121

**Comment by ewoiset** [comment]
postponed
