### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#132]
- [x] exported sources can't be imported anymore
- [x] Frontend: Menu Bar icon not working anymore
- [x] Import/Export button (OSINT sources) are sorted vertically (not next to each other) --> this only happens when one changes from assess tab to osint sources 
- [ ] Tags are displayed in next line in some asses news items (see screenshot underneath)
- [ ] read button shown twice in news item (see screenshot)
- [ ]  "More" view in news item closes after up/downgrading --> wished? 
- [ ] In the Assess items: in the drop down menu of each item is "mark as read" -- this button does not change dynamically when you want to mark it as unread
- [ ] In Report Types: "New item" -> "+New Attribute Group" -> "+ New Attribute" -- the pop-up menu width dynamically adjusts to the text width of the dropdown menu "attribute" (Min and Max occurrence does not fit when selecting CPE or any short attribute)
- [x] Analyze: report item can't be "unchecked" as incomplete after marking as "Complete"
- [x] Analyze: Filter "incomplete" does not filter out "completed=false" report items
- [x] Analyze: in a report item the  "Completed" text is rendered as "Complete\nd"

**Comment by ewoiset** [comment]
![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/861c93ee-bd8e-47b5-b508-6be4eea5cbbc)

**Comment by ewoiset** [comment]
![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/bfcfd9ce-c2be-44f4-97f1-26018cd82752)

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/28)
