### ISSUE TITLE
Refactor ForeignKey on delete behavior 

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#136]
- [ ] Refactor on delete behavior -> cascade, set null, default (error)
- [ ] handle error message when on delete throws error 
- [ ] check all foreign keys

related issue: https://github.com/ait-cs-IaaS/Taranis-NG/issues/117

![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/65f59246-5e83-4769-b344-3cb026707bd2)

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/26)
