### ISSUE TITLE
Autopublish

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#138]
Automatically republish a report if the "autopublish" checkbox is set.

Everytime a report changes used in a Product that has the "autopublish" set to true. publish that report.

Update [product.py](https://github.com/ait-cs-IaaS/Taranis-NG/blob/00c30bd85b1f5cc98d188f95c6bb8c0a0395acaf/src/core/core/model/product.py) with: 

    autopublish = db.Coulmn(db.Boolean, default=False)

Update [ProductItem.vue](https://github.com/ait-cs-IaaS/Taranis-NG/blob/6f4f0704ba5c41ec1dc30ba08768482c4d44f475/src/gui/src/components/publish/ProductItem.vue) with:

```
            <v-checkbox v-model="product.autopublish" label="Autopublish" />
```

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/25)
