### ISSUE TITLE
Extend schema tests

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#149]
- [ ] Complete endpoint testing in tests/test_schema.py 
- [ ] Check for which config/ endpoints testing is necessary
- [ ] Adapt "Component" in yaml to complete all tests (as done with asses and analyze)

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/19)
