### ISSUE TITLE
Write worker tests

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#152]
- [ ] write celery tests e.g https://docs.celeryq.dev/en/v5.2.6/userguide/testing.html#celery-worker-embed-live-worker
- [ ] use e.g. flask minimal application (+add routes) for a mocking core API (no auth needed)

Note: 
- collector, presenter, publish, bots --> only logical difference in tasks - otherwise the same

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/17)
