### ISSUE TITLE
BUG: PROXY_SERVER is not used in the RSS feed collector

### ISSUE THREAD

**Issue by waldbauer-certat** [ait-cs-IaaS/Taranis-NG#160]
Hello,

somehow the PROXY_SERVER variable is not being used in the RSS feed collector. A temporary fix is to set the environment variable in the docker-compose `HTTPS_PROXY=http://proxy.server:80`, but this shouldnt be done this way because we may collect data from HTTP sources aswell, which wouldnt work.

Thanks

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/11)
