### ISSUE TITLE
Default Login for Docker Deployment

### ISSUE THREAD

**Issue by mik-at** [ait-cs-IaaS/Taranis-NG#173]
Hi!

Not sure if it's an issue or it is just me.
I used this guide to deploy the docker containers: https://github.com/ait-cs-IaaS/Taranis-NG/wiki/Deployment

But I'm stuck on the login screen.

The default credentials user / user and admin / admin from https://github.com/SK-CERT/Taranis-NG are not working.
I also tried to look at the postgres database and found that a user taranis is in the "user" table, but couldn't find a password.
Also the "docker exec -it <container> python manage.py" command isn't working as it can not find the manage.py.

Can you maybe help me to find the default login for the docker deployment?

Thanks!

**Comment by b3n4kh** [comment]
The default users admin/admin should work, but we are currently in an alpha release state.

 https://github.com/SK-CERT/Taranis-NG there is currently less then 5% shared code with the upstream, manage.py dosen't exist, anymore, everything it did is already automated.
 
 Our current plan is to have our first stable release at the end of march 2024, have a look at https://github.com/orgs/ait-cs-IaaS/projects/2 for details

**Comment by mik-at** [comment]
Thanks! I redeployed everything again and now admin/admin works.
Maybe it didn't work because it takes up all CPU and RAM of my VM at the first launch and I did a reset of the VM.
