### ISSUE TITLE
add a diagram showing the development of a story to the storycard / storydetail

### ISSUE THREAD

**Issue by b3n4kh** [ait-cs-IaaS/Taranis-NG#43]
Finalize development of https://github.com/ait-cs-IaaS/Taranis-NG/blob/awake/src/gui/src/components/assess/card/WeekChart.vue

Have a look at switching charts to BarChart with Trendline: https://www.npmjs.com/package/chartjs-plugin-trendline

**Comment by ewoiset** [comment]
ideas: 
- display daily incremented sum as bar chart (weekly incremented sum not necessary) 
- moving/rolling average displayed as line (what time range?) 
- linear / polygon trend line 
- display bar exceeding threshold in different color 
- hover functionality needed? 
- display last 7 days of data 
- 
 
packages/plugins:
- https://github.com/HarryStevens/d3-regression
- https://observablehq.com/@climatelab/leaf-appearance-and-temperature
- https://observablehq.com/@observablehq/plot-linear-regression?collection=@observablehq/plot

**Comment by b3n4kh** [comment]
See for example render functions:
https://github.com/ait-cs-IaaS/koord2ool/blob/main/src/helpers/chartFunctions.ts#LL190C17-L190C38

See https://github.com/ait-cs-IaaS/koord2ool/blob/main/src/components/surveys/line-options.ts for line options

**Comment by ewoiset** [comment]
Split up StoryCard and DataPointsCard (dashboard)
