### ISSUE TITLE
migrate workers from nodes to "workers"

### ISSUE THREAD

**Issue by b3n4kh** [ait-cs-IaaS/Taranis-NG#51]
Migrate the "bots" & "collectors" to "workers" that get their input via rabbitMQ.

Implementing the "Subscriber" from the new Pub/Sub Queue: https://github.com/ait-cs-IaaS/Taranis-NG/issues/48

**Comment by b3n4kh** [comment]
This will solve #83

**Comment by b3n4kh** [comment]
This task could be simplified if not everything is migrated, but only what is strictly necessary for AWAKE. The rest could be a separate issue for later

**Comment by ewoiset** [comment]
@b3n4kh  current db structure: 

![Image](https://github.com/ait-cs-IaaS/Taranis-NG/assets/88492381/1868a3a2-03f0-47a9-8596-7afdb5d590ee)
