### ISSUE TITLE
NotificationTemplate: Update & delete not working 

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#63]
Update and delete of Notification templates not working with following error messages: 

```
AttributeError: type object 'NotificationTemplate' has no attribute 'delete'
AttributeError: type object 'NotificationTemplate' has no attribute 'update'

```

```
DELETE http://localhost:5000/api/v1/asset-notification-templates/1 500 (INTERNAL SERVER ERROR)
PUT http://localhost:5000/api/v1/asset-notification-templates/1 500 (INTERNAL SERVER ERROR)
```

Furthermore, adding recipients should be refactored

**Comment by b3n4kh** [comment]
Consider removing this altogether? I don't see the purpose? What is this even used for?

**Comment by ewoiset** [comment]
Notofication Template has been removed. It will be replaced by an "autopublish" feature as described in:
