### ISSUE TITLE
Form still displayed after add/delete

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#64]
**Unwanted behavior:** 

1.  Form still displayed after add/delete. Occurs at:

- all config endpoints (e.g. users, roles, product types etc)
- analyse

2. Table does not automatically update after new item is created. Occurs at:
- config/users

**Details:** 
ADD: 
-   when successfully creating a new item, submission form and button should not be displayed anymore. 

DELETE: 
reproduce (e.g. production type): 
- create product type 
- click on product type to display details/edit (image 01) 
- while details are still displayed, delete product type
- details are still displayed, edit not possible anymore (error as element non existent)  --> image 02

wanted behavior: 
- no product type info displayed of deleted elements / form & button removed after add / delete

add: 
![Screenshot from 2023-04-11 12-00-42](https://user-images.githubusercontent.com/88492381/231127526-6c6f266e-ea3e-47cf-9a54-887db252d0c0.png)

delete 01: 
![01](https://user-images.githubusercontent.com/88492381/230130445-d1e6cddc-7714-458c-8c99-8e17d7247424.png)

delete 02:
![02](https://user-images.githubusercontent.com/88492381/230130456-f3d84958-d910-40c9-b24c-5dfd437d15d7.png)

**Comment by b3n4kh** [comment]
Fixed in https://github.com/ait-cs-IaaS/Taranis-NG/blob/migration_on_delete/src/gui/src/views/admin/OSINTSourcesView.vue#L20C22-L20C22

See "showForm" variable

**Comment by b3n4kh** [comment]
Fixed at some point...
