### ISSUE TITLE
Assess Filter: tag issues

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#81]
- [ ]  Adding a second tag in assess' filter not working - second tag does not change the result

Issues in backend via: 
http://taranis/api/assess/tags
&
http://taranis/api/assess/news-item-aggregates?tags=Python&tags=End-of-Day

**Comment by b3n4kh** [comment]
As a work around make tagfilter single select until this can be resolved.

https://github.com/ait-cs-IaaS/Taranis-NG/blob/c86d96b262667f06acca3f96a69d779e852b353e/src/gui/src/components/assess/filter/tagFilter.vue#LL18C1-L19C1

**Comment by b3n4kh** [comment]
Fixed in https://github.com/ait-cs-IaaS/Taranis-NG/commit/744ef038bd92cad47f11afead55458a8298e900d
