### ISSUE TITLE
Assets' text search displays text

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#82]
Assets' text search displays text underneath "New asset group" button

![Screenshot from 2023-05-03 16-10-21](https://user-images.githubusercontent.com/88492381/235941203-d44bd646-57c6-4067-8e4e-de9bcc35d4f8.png)

**Comment by b3n4kh** [comment]
Kamino cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/57)
