### ISSUE TITLE
Update MISP Presenter template 

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#91]
Review and update misp template in presenter, to export all relevant information - tags, topics, etc...

Using https://pymisp.readthedocs.io/en/latest/ in https://github.com/ait-cs-IaaS/Taranis-NG/blob/awake/src/worker/worker/publishers/misp_publisher.py to publish a json created by:

https://github.com/ait-cs-IaaS/Taranis-NG/blob/awake/src/core/core/managers/workers_pre_seed.py#L286C6-L286C6

with this template: https://github.com/ait-cs-IaaS/Taranis-NG/blob/awake/src/core/core/static/presenter_templates/misp_template.json

So the main change for this issue is to adapt the [misp_template.json](https://github.com/ait-cs-IaaS/Taranis-NG/blob/awake/src/core/core/static/presenter_templates/misp_template.json) to include the "relevant information".

See https://www.misp-project.org/openapi/#tag/Events/operation/addEvent for available fields

Adding the actual stories would be a good first improvement

```json
        {% for story in report_item.news_item_aggregates %}
        {{ story }}
        {% endfor %}
```

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/40)
