### ISSUE TITLE
Add/edit product

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#94]
add following functionality to http://localhost:8082/product/{id} - same for "new" and "update"
- display report items as table (similar to "config/reportitems/attributes") 
- rendering product in frontend
- enable functionality

also 
-  AnalyzeView --> "Create product" button in table (see screenshot in comment) not working --> `Uncaught Error: Missing required param "id"`

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/37)
